# Generated by Django 5.1.4 on 2025-04-17 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_group_options_alter_customuser_role_and_more'),
        ('schedule', '0002_alter_classes_group_alter_classes_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.student', verbose_name='Курс'),
        ),
    ]
