# Generated by Django 5.1.4 on 2025-04-17 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_group_options_alter_customuser_role_and_more'),
        ('schedule', '0003_classes_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.student', verbose_name='Курс'),
        ),
    ]
