# Generated by Django 5.1.4 on 2025-04-17 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_customuser_role_alter_student_year'),
        ('schedule', '0004_alter_classes_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.student', verbose_name='Курс'),
        ),
    ]
