# Generated by Django 5.1.4 on 2025-04-17 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_alter_classes_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classes',
            name='year',
        ),
    ]
