# Generated by Django 5.1.4 on 2025-03-21 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0008_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='grade',
            field=models.CharField(choices=[('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('pass', 'Зачёт'), ('fail', 'Незачёт')], max_length=5),
        ),
        migrations.AlterField(
            model_name='grade',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
