# Generated by Django 5.1.4 on 2025-04-11 08:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('faculty', models.CharField(max_length=150)),
                ('department', models.CharField(max_length=150)),
                ('experience_years', models.PositiveIntegerField()),
                ('position', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('year', models.PositiveIntegerField()),
                ('faculty', models.CharField(max_length=150)),
                ('department', models.CharField(max_length=150)),
                ('record_book_number', models.CharField(max_length=50)),
                ('citizenship', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('admission_year', models.PositiveIntegerField()),
                ('gpa', models.DecimalField(decimal_places=2, max_digits=4)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.group')),
            ],
        ),
    ]
