# Generated by Django 5.1.4 on 2025-04-11 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_teacher_alter_customuser_id_alter_group_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='group',
        ),
    ]
