# Generated by Django 5.1.4 on 2025-04-15 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_department_faculty_alter_student_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='old_department',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='old_faculty',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='old_department',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='old_faculty',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
