# Generated by Django 5.1.4 on 2025-04-16 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_student_old_department_student_old_faculty_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='gpa',
        ),
        migrations.RemoveField(
            model_name='student',
            name='old_department',
        ),
        migrations.RemoveField(
            model_name='student',
            name='old_faculty',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='old_department',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='old_faculty',
        ),
    ]
