# Generated by Django 5.1.4 on 2025-04-16 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_group_options_alter_department_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={},
        ),
        migrations.AddField(
            model_name='direction',
            name='education_level',
            field=models.CharField(choices=[('bachelor', 'Бакалавриат'), ('specialist', 'Специалитет'), ('master', 'Магистратура')], default='bachelor', max_length=20, verbose_name='Уровень образования'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название кафедры'),
        ),
        migrations.AlterField(
            model_name='direction',
            name='code',
            field=models.CharField(max_length=10, verbose_name='Код направления'),
        ),
        migrations.AlterField(
            model_name='direction',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directions', to='accounts.faculty'),
        ),
        migrations.AlterField(
            model_name='direction',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название направления'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название факультета'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название профиля'),
        ),
    ]
