# Generated by Django 5.1.4 on 2025-04-17 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_customuser_role_alter_student_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='year',
            field=models.PositiveIntegerField(null=True, verbose_name='Курс'),
        ),
    ]
