# Generated by Django 5.1.4 on 2025-05-23 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_student_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.department', verbose_name='Кафедра'),
        ),
    ]
