# Generated by Django 5.1.4 on 2025-05-28 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_vitrina'),
    ]

    operations = [
        migrations.AddField(
            model_name='vitrina',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='project_covers/', verbose_name='Обложка проекта'),
        ),
    ]
