# Generated by Django 5.1.4 on 2025-06-02 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_vitrina_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='vitrina',
            name='status',
            field=models.CharField(choices=[('pending', 'На модерации'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], default='pending', max_length=10),
        ),
    ]
