# Generated by Django 5.1.4 on 2025-04-16 18:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0002_grade_is_exam_alter_grade_grade_passfailrecord'),
        ('schedule', '0002_alter_classes_group_alter_classes_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='grade',
            field=models.PositiveSmallIntegerField(verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='is_exam',
            field=models.BooleanField(default=False, verbose_name='Экзамен'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades_as_student', to=settings.AUTH_USER_MODEL, verbose_name='Студент'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.classes', verbose_name='Предмет'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades_as_teacher', to=settings.AUTH_USER_MODEL, verbose_name='Преподаватель'),
        ),
        migrations.AlterField(
            model_name='passfailrecord',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='passfailrecord',
            name='status',
            field=models.CharField(choices=[('pass', 'Зачёт'), ('fail', 'Незачёт')], max_length=5, verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='passfailrecord',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pass_fail_records', to=settings.AUTH_USER_MODEL, verbose_name='Студент'),
        ),
        migrations.AlterField(
            model_name='passfailrecord',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.classes', verbose_name='Предмет'),
        ),
        migrations.AlterField(
            model_name='passfailrecord',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pass_fail_as_teacher', to=settings.AUTH_USER_MODEL, verbose_name='Преподаватель'),
        ),
    ]
