# Generated by Django 5.1.4 on 2025-04-17 10:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0003_alter_grade_date_alter_grade_grade_and_more'),
        ('schedule', '0002_alter_classes_group_alter_classes_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pass', 'Зачёт'), ('fail', 'Незачёт'), ('5', 'Отлично'), ('4', 'Хорошо'), ('3', 'Удовлетворительно')], max_length=5, verbose_name='Оценка')),
                ('date', models.DateField(verbose_name='Дата')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_records', to=settings.AUTH_USER_MODEL, verbose_name='Студент')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.classes', verbose_name='Предмет')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_as_teacher', to=settings.AUTH_USER_MODEL, verbose_name='Преподаватель')),
            ],
        ),
        migrations.DeleteModel(
            name='PassFailRecord',
        ),
    ]
