# Generated by Django 5.1.4 on 2025-04-17 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0004_exam_delete_passfailrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='is_exam',
        ),
        migrations.AlterField(
            model_name='grade',
            name='grade',
            field=models.CharField(choices=[('5', 'Отлично'), ('4', 'Хорошо'), ('3', 'Удовлетворительно'), ('2', 'Неудовлетворительно'), ('1', 'Неверно')], max_length=1, verbose_name='Оценка'),
        ),
    ]
